
module.exports = {
  1: "(MORNING) Har du tagit en paus?",
  2: "(MORNING) Har du haft högt fokus på den enskilt för stunden aktuella uppgiften?",
  3: "(MORNING) Har du blivit störd av dina telefon eller liknande när du varit fokuserad?",
  4: "(MORNING) Har du skjutit fram något som du skulle kunnat göra nu?",
  5: "(MORNING) Har du ljugit för dig själv, eller någon annan?",
  6: "(MORNING) Är din arbetsyta stökig just nu?",
  7: "(MORNING) Har du ätit?",
  8: "(MORNING) Känner du dig proppmätt?",
  9: "(MORNING) Har du druckit vatten?",
  10: "(MORNING) ( if smoker ) Har du rökt?",
  11: "(MORNING) Har du tränat?",
  12: "(MORNING) Har du ätit sötsaker?",
  13: "(MORNING) Kollade du email/sociala medier innan du åt frukost/tränade?",
  14: "(MORNING) Har du en klar bild av vad du ska åstadkomma idag?",
  15: "(MORNING) ( if nykterist ) Drack du alkohol igår ?",
  16: "(MORNING) Blev du full igår ?",
  17: "(MORNING) Har du sovit åtta timmar eller mer inatt ?",
  18: "(MORNING) Hur mår du? ( 1 - 4 )",
  19: "(MORNING) Känner du dig stressad? ( 1 - 4 )",
  20: "(LUNCH) Kommentar för din egen skull ( Fritext )",
  21: "(LUNCH) Har du tagit en paus?",
  22: "(LUNCH) Har du haft högt fokus på den enskilt för stunden aktuella uppgiften?",
  23: "(LUNCH) Har du blivit störd av dina telefon eller liknande när du varit fokuserad?",
  24: "(LUNCH) Har du skjutit fram något som du skulle kunnat göra nu?",
  25: "(LUNCH) Har du ljugit för dig själv, eller någon annan?",
  26: "(LUNCH) Är din arbetsyta stökig just nu?",
  27: "(LUNCH) Har du ätit?",
  28: "(LUNCH) Känner du dig proppmätt?",
  29: "(LUNCH) Har du druckit vatten?",
  30: "(LUNCH) ( if smoker ) Har du rökt?",
  31: "(LUNCH) Har du tränat?",
  32: "(LUNCH) Har du ätit sötsaker?",
  33: "(LUNCH) Har du druckit mer än två koppar kaffe?",
  34: "(LUNCH) Hur mår du? ( 1 - 4 )",
  35: "(LUNCH) Känner du dig stressad? ( 1 - 4 )",
  36: "(DINNER) Kommentar för din egen skull ( Fritext )",
  37: "(DINNER) Har du tagit en paus?",
  38: "(DINNER) Har du haft högt fokus på den enskilt för stunden aktuella uppgiften?",
  39: "(DINNER) Har du blivit störd av dina telefon eller liknande när du varit fokuserad?",
  40: "(DINNER) Har du skjutit fram något som du skulle kunnat göra nu?",
  41: "(DINNER) Har du ljugit för dig själv, eller någon annan?",
  42: "(DINNER) Är din arbetsyta stökig just nu?",
  43: "(DINNER) Har du ätit?",
  44: "(DINNER) Känner du dig proppmätt?",
  45: "(DINNER) Har du druckit vatten?",
  46: "(DINNER) ( if smoker ) Har du rökt?",
  47: "(DINNER) Har du tränat?",
  48: "(DINNER) Har du ätit sötsaker?",
  49: "(DINNER) Har du druckit mer än två koppar kaffe?",
  50: "(DINNER) Hur mår du? ( 1 - 4 )",
  51: "(DINNER) Känner du dig stressad? ( 1 - 4 )",
  52: "(ALL DAY) Kommentar för din egen skull ( Fritext )",
  53: "(ALL DAY) När jobbade du med det mest utmanande under dagen? (Innan lunch / Efter Lunch)",
  54: "(ALL DAY) Har du kollat på TV / Netflix / YouTube mer än en timme idag?",
  55: "(ALL DAY) Har du kollat publika sociala media kanaler mer än … idag?",
  56: "(ALL DAY) Har du tagit dig an att göra något, som du nu ångrar?",
  57: "(ALL DAY) Har du druckit två liter vatten eller mer idag?",
  58: "(ALL DAY) Hur har du mått idag? ( 1 - 4 )",
  59: "(ALL DAY) Har du känt dig stressad idag? ( 1 - 4 )",
  60: "(ALL DAY) Kommentar för din egen skull ( Fritext )"
}
