
module.exports = {
  1: "Har du tagit en paus?",
  2: "Har du haft högt fokus på den enskilt för stunden aktuella uppgiften?",
  3: "Har du blivit störd av dina telefon eller liknande när du varit fokuserad?",
  4: "Har du skjutit fram något som du skulle kunnat göra nu?",
  5: "Har du ljugit för dig själv, eller någon annan?",
  6: "Är din arbetsyta stökig just nu?",
  7: "Har du ätit?",
  8: "Känner du dig proppmätt?",
  9: "Har du druckit vatten?",
  10: "( if smoker ) Har du rökt?",
  11: "Har du tränat?",
  12: "Har du ätit sötsaker?",
  13: "Kollade du email/sociala medier innan du åt frukost/tränade?",
  14: "Har du en klar bild av vad du ska åstadkomma idag?",
  15: "( if nykterist ) Drack du alkohol igår ?",
  16: "Blev du full igår ?",
  17: "Har du sovit åtta timmar eller mer inatt ?",
  18: "Hur mår du? ( 1 - 4 )",
  19: "Känner du dig stressad? ( 1 - 4 )",
  20: "Kommentar för din egen skull ( Fritext )",
  21: "Har du tagit en paus?",
  22: "Har du haft högt fokus på den enskilt för stunden aktuella uppgiften?",
  23: "Har du blivit störd av dina telefon eller liknande när du varit fokuserad?",
  24: "Har du skjutit fram något som du skulle kunnat göra nu?",
  25: "Har du ljugit för dig själv, eller någon annan?",
  26: "Är din arbetsyta stökig just nu?",
  27: "Har du ätit?",
  28: "Känner du dig proppmätt?",
  29: "Har du druckit vatten?",
  30: "( if smoker ) Har du rökt?",
  31: "Har du tränat?",
  32: "Har du ätit sötsaker?",
  33: "Har du druckit mer än två koppar kaffe?",
  34: "Hur mår du? ( 1 - 4 )",
  35: "Känner du dig stressad? ( 1 - 4 )",
  36: "Kommentar för din egen skull ( Fritext )",
  37: "Har du tagit en paus?",
  38: "Har du haft högt fokus på den enskilt för stunden aktuella uppgiften?",
  39: "Har du blivit störd av dina telefon eller liknande när du varit fokuserad?",
  40: "Har du skjutit fram något som du skulle kunnat göra nu?",
  41: "Har du ljugit för dig själv, eller någon annan?",
  42: "Är din arbetsyta stökig just nu?",
  43: "Har du ätit?",
  44: "Känner du dig proppmätt?",
  45: "Har du druckit vatten?",
  46: "( if smoker ) Har du rökt?",
  47: "Har du tränat?",
  48: "Har du ätit sötsaker?",
  49: "Har du druckit mer än två koppar kaffe?",
  50: "Hur mår du? ( 1 - 4 )",
  51: "Känner du dig stressad? ( 1 - 4 )",
  52: "Kommentar för din egen skull ( Fritext )",
  53: "När jobbade du med det mest utmanande under dagen? (Innan lunch / Efter Lunch)",
  54: "Har du kollat på TV / Netflix / YouTube mer än en timme idag?",
  55: "Har du kollat publika sociala media kanaler mer än … idag?",
  56: "Har du tagit dig an att göra något, som du nu ångrar?",
  57: "Har du druckit två liter vatten eller mer idag?",
  58: "Hur har du mått idag? ( 1 - 4 )",
  59: "Har du känt dig stressad idag? ( 1 - 4 )",
  60: "Kommentar för din egen skull ( Fritext )"
}
